CREATE TABLE VENDAS (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL
);

INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor) 
VALUES 
    ('Notebook Dell', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24"', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam HD', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna');

-- Exec 1
SELECT produto, valor FROM VENDAS WHERE valor >(SELECT MIN(valor) FROM VENDAS WHERE categoria = 'Eletrônicos');

-- Exec 2
SELECT vendedor, produto, valor 
FROM VENDAS 
WHERE valor = (SELECT MAX(valor) FROM VENDAS);

-- Exec 3
SELECT categoria, SUM(valor) as vendido 
FROM VENDAS 
WHERE valor > (SELECT AVG(valor) as media 
FROM VENDAS)
GROUP BY categoria;

-- Exec 4
SELECT valor, produto, vendedor, RANK() OVER (ORDER BY valor DESC) as rank FROM VENDAS FETCH FIRST 3 ROWS ONLY;